### ISSUE TITLE
歌曲同时播放

### ISSUE THREAD

**Issue by liuxuan00** [lilongweidev/GoodMusic#2]

**Comment by liuxuan00** [comment]
> 播放音乐后 滑动下方控件进行切歌 之前的歌曲没有关闭

**Comment by lilongweidev** [comment]
你可以调试看看，这个项目没有后续了。




Li
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lilongweidev/GoodMusic"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月8日(星期一) 中午11:47
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[lilongweidev/GoodMusic] 歌曲同时播放 (Issue #2)





 
播放音乐后  滑动下方控件进行切歌   之前的歌曲没有关闭

**Comment by liuxuan00** [comment]
找到问题了    是因为LocalMusicActivity 和 MainActivity 这两个页面是独立的  所以会同时播放
